name: Health Check

on:
  schedule:
    - cron:  '0 0-23 * * *'

jobs:
  healtchcheck_job:
    steps:
    - name: Check the deployed app URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://glacial-savannah-77090.herokuapp.com/
        max-attempts: 3 
        retry-delay: 5s

